import 'package:flutter/material.dart';

const Map<String, Color> defaultVscodeTheme = {        
    "foreground" : Color(0xFFCCCCCC),
    "disabledForeground" : Color(0xCCCCCC80),
    "errorForeground" : Color(0xFFF48771),
    "descriptionForeground" : Color(0xB2CCCCCC),
    "icon.foreground" : Color(0xFFC5C5C5),
    "focusBorder" : Color(0xFF007FD4),
    "contrastBorder" : Colors.black,
    "contrastActiveBorder" : Colors.black,
    "selection.background" : Colors.black,
    "textSeparator.foreground" : Color(0xffffff2e),
    "textLink.foreground" : Color(0xFF3794FF),
    "textLink.activeForeground" : Color(0xFF3794FF),
    "textPreformat.foreground" : Color(0xFFD7BA7D),
    "textBlockQuote.background" : Color(0x7f7f7f1a),
    "textBlockQuote.border" : Color(0x007acc80),
    "textCodeBlock.background" : Color(0x0a0a0a66),
    "widget.shadow" : Color(0xB2000000),
    "input.background" : Color(0xFF3C3C3C),
    "input.foreground" : Color(0xFFCCCCCC),
    "input.border" : Colors.black,
    "inputOption.activeBorder" : Color(0x007ACC00),
    "inputOption.hoverBackground" : Color(0x5a5d5e80),
    "inputOption.activeBackground" : Color(0xB2007FD4),
    "inputOption.activeForeground" : Colors.white,
    "input.placeholderForeground" : Color(0xB2CCCCCC),
    "inputValidation.infoBackground" : Color(0xFF063B49),
    "inputValidation.infoForeground" : Colors.black,
    "inputValidation.infoBorder" : Color(0xFF007acc),
    "inputValidation.warningBackground" : Color(0xFF352A05),
    "inputValidation.warningForeground" : Colors.black,
    "inputValidation.warningBorder" : Color(0xFFB89500),
    "inputValidation.errorBackground" : Color(0xFF5A1D1D),
    "inputValidation.errorForeground" : Colors.black,
    "inputValidation.errorBorder" : Color(0xFFBE1100),
    "dropdown.background" : Color(0xFF3C3C3C),
    "dropdown.listBackground" : Colors.black,
    "dropdown.foreground" : Color(0xFFF0F0F0),
    "dropdown.border" : Color(0xFF3C3C3C),
    "checkbox.background" : Color(0xFF3C3C3C),
    "checkbox.foreground" : Color(0xFFF0F0F0),
    "checkbox.border" : Color(0xFF3C3C3C),
    "button.foreground" : Colors.white,
    "button.background" : Color(0xFF0E639C),
    "button.hoverBackground" : Color(0xFF2277B0),
    "button.border" : Colors.black,
    "button.secondaryForeground" : Colors.white,
    "button.secondaryBackground" : Color(0xFF3A3D41),
    "button.secondaryHoverBackground" : Color(0xFF4E5155),
    "badge.background" : Color(0xFF4D4D4D),
    "badge.foreground" : Colors.white,
    "scrollbar.shadow" : Color(0xFF000000),
    "scrollbarSlider.background" : Color(0x66797979),
    "scrollbarSlider.hoverBackground" : Color(0xB2646464),
    "scrollbarSlider.activeBackground" : Color(0x66BFBFBF),
    "progressBar.background" : Color(0xFF0E70C0),
    "editorError.background" : Colors.black,
    "editorError.foreground" : Color(0xFFF14C4C),
    "editorError.border" : Colors.black,
    "editorWarning.background" : Colors.black,
    "editorWarning.foreground" : Color(0xFFCCA700),
    "editorWarning.border" : Colors.black,
    "editorInfo.background" : Colors.black,
    "editorInfo.foreground" : Color(0xFF3794FF),
    "editorInfo.border" : Colors.black,
    "editorHint.foreground" : Color(0xB2EEEEEE),
    "editorHint.border" : Colors.black,
    "sash.hoverBorder" : Color(0xFF007FD4),
    "editor.background" : Color(0xFF1E1E1E),
    "editor.foreground" : Color(0xFFBBBBBB),
    "editorWidget.background" : Color(0xFF252526),
    "editorWidget.foreground" : Color(0xFFCCCCCC),
    "editorWidget.border" : Color(0xFF454545),
    "editorWidget.resizeBorder" : Colors.black,
    "quickInput.background" : Color(0xFF252526),
    "quickInput.foreground" : Color(0xFFCCCCCC),
    "quickInputTitle.background" : Color.fromARGB(27, 255, 255, 255),
    "pickerGroup.foreground" : Color(0xFF3794FF),
    "pickerGroup.border" : Color(0xFF3F3F46),
    "keybindingLabel.background" : Color.fromARGB(44, 128, 128, 128),
    "keybindingLabel.foreground" : Color(0xFFCCCCCC),
    "keybindingLabel.border" : Color.fromARGB(153, 51, 51, 51),
    "keybindingLabel.bottomBorder" : Color.fromARGB(153, 68, 68, 68),
    "editor.selectionBackground" : Color(0xFF264F78),
    "editor.selectionForeground" : Colors.black,
    "editor.inactiveSelectionBackground" : Color(0xB2264F78),
    "editor.selectionHighlightBackground" : Color(0xFF264F78),
    "editor.selectionHighlightBorder" : Colors.black,
    "editor.findMatchBackground" : Color(0xFF515C6A),
    "editor.findMatchHighlightBackground" : Color(0xEA5C0055),
    "editor.findRangeHighlightBackground" : Color(0x3a3d4166),
    "editor.findMatchBorder" : Colors.black,
    "editor.findMatchHighlightBorder" : Colors.black,
    "editor.findRangeHighlightBorder" : Colors.black,
    "searchEditor.findMatchBackground" : Color(0xB25C0055),
    "searchEditor.findMatchBorder" : Colors.black,
    "editor.hoverHighlightBackground" : Color(0x264f7840),
    "editorHoverWidget.background" : Color(0xFF252526),
    "editorHoverWidget.foreground" : Color(0xFFCCCCCC),
    "editorHoverWidget.border" : Color(0xFF454545),
    "editorHoverWidget.statusBarBackground" : Color(0xFF39393A),
    "editorLink.activeForeground" : Color(0xFF4E94CE),
    "editorInlayHint.foreground" : Color(0xB2FFFFFF),
    "editorInlayHint.background" : Color(0xB24D4D4D),
    "editorInlayHint.typeForeground" : Color(0xB2FFFFFF),
    "editorInlayHint.typeBackground" : Color(0xB24D4D4D),
    "editorInlayHint.parameterForeground" : Color(0xB2FFFFFF),
    "editorInlayHint.parameterBackground" : Color(0xB24D4D4D),
    "editorLightBulb.foreground" : Color(0xFFFFCC00),
    "editorLightBulbAutoFix.foreground" : Color(0xFF75BEFF),
    "diffEditor.insertedTextBackground" :  Color.fromARGB(51, 155, 185, 85),
    "diffEditor.removedTextBackground" :  Color.fromARGB(51, 255, 0, 0),
    "diffEditor.insertedLineBackground" : Colors.black,
    "diffEditor.removedLineBackground" : Colors.black,
    "diffEditorGutter.insertedLineBackground" : Colors.black,
    "diffEditorGutter.removedLineBackground" : Colors.black,
    "diffEditorOverview.insertedForeground" : Colors.black,
    "diffEditorOverview.removedForeground" : Colors.black,
    "diffEditor.insertedTextBorder" : Colors.black,
    "diffEditor.removedTextBorder" : Colors.black,
    "diffEditor.border" : Colors.black,
    "diffEditor.diagonalFill" : Color(0xcccccc33),
    "list.focusBackground" : Colors.black,
    "list.focusForeground" : Colors.black,
    "list.focusOutline" : Color(0xFF007FD4),
    "list.activeSelectionBackground" : Color(0xFF094771),
    "list.activeSelectionForeground" : Colors.white,
    "list.activeSelectionIconForeground" : Colors.black,
    "list.inactiveSelectionBackground" : Color(0xFF37373D),
    "list.inactiveSelectionForeground" : Colors.black,
    "list.inactiveSelectionIconForeground" : Colors.black,
    "list.inactiveFocusBackground" : Colors.black,
    "list.inactiveFocusOutline" : Colors.black,
    "list.hoverBackground" : Color(0xFF2A2D2E),
    "list.hoverForeground" : Colors.black,
    "list.dropBackground" : Color(0xFF062F4A),
    "list.highlightForeground" : Color(0xFF18A3FF),
    "list.focusHighlightForeground" : Color(0xFF18A3FF),
    "list.invalidItemForeground" : Color(0xFFB89500),
    "list.errorForeground" : Color(0xFFF88070),
    "list.warningForeground" : Color(0xFFCCA700),
    "listFilterWidget.background" : Color(0xFF653723),
    "listFilterWidget.outline" : Colors.transparent,
    "listFilterWidget.noMatchesOutline" : Color(0xFFBE1100),
    "list.filterMatchBackground" : Color(0xEA5C0055),
    "list.filterMatchBorder" : Colors.black,
    "tree.indentGuidesStroke" : Color(0xFF585858),
    "tree.tableColumnsBorder" : Color(0xCCCCCC20),
    "tree.tableOddRowsBackground" : Color(0xB2CCCCCC),
    "list.deemphasizedForeground" : Color(0xFF8C8C8C),
    "quickInput.list.focusBackground" : Colors.black,
    "quickInputList.focusForeground" : Colors.white,
    "quickInputList.focusIconForeground" : Colors.black,
    "quickInputList.focusBackground" : Colors.black,
    "menu.border" : Colors.black,
    "menu.foreground" : Color(0xFFF0F0F0),
    "menu.background" : Color(0xFF3C3C3C),
    "menu.selectionForeground" : Colors.white,
    "menu.selectionBackground" : Color(0xFF094771),
    "menu.selectionBorder" : Colors.black,
    "menu.separatorBackground" : Color(0xFFBBBBBB),
    "toolbar.hoverBackground" : Color(0x5a5d5e50),
    "toolbar.hoverOutline" : Colors.black,
    "toolbar.activeBackground" : Color(0x5a717264),
    "editor.snippetTabstopHighlightBackground" : Color.fromARGB(77, 124, 124, 124),
    "editor.snippetTabstopHighlightBorder" : Colors.black,
    "editor.snippetFinalTabstopHighlightBackground" : Colors.black,
    "editor.snippetFinalTabstopHighlightBorder" : Color(0xFF525252),
    "breadcrumb.foreground" : Color(0xB2CCCCCC),
    "breadcrumb.background" : Color(0xFF1E1E1E),
    "breadcrumb.focusForeground" : Color(0xFFE0E0E0),
    "breadcrumb.activeSelectionForeground" : Color(0xFFE0E0E0),
    "breadcrumbPicker.background" : Color(0xFF252526),
    "merge.currentHeaderBackground" : Color(0xB240C8AE),
    "merge.currentContentBackground" : Color(0x6640C8AE),
    "merge.incomingHeaderBackground" : Color(0xB240A6FF),
    "merge.incomingContentBackground" : Color(0x6640A6FF),
    "merge.commonHeaderBackground" : Color(0xB2606060),
    "merge.commonContentBackground" : Color(0x66606060),
    "merge.border" : Colors.black,
    "editorOverviewRuler.currentContentForeground" : Color(0x6640C8AE),
    "editorOverviewRuler.incomingContentForeground" : Color(0x6640A6FF),
    "editorOverviewRuler.commonContentForeground" : Color(0x66606060),
    "editorOverviewRuler.findMatchForeground" : Color(0xd186167e),
    "editorOverviewRuler.selectionHighlightForeground" : Color(0xA0A0A0CC),
    "minimap.findMatchHighlight" : Color(0xFFd18616),
    "minimap.selectionOccurrenceHighlight" : Color(0xFF676767),
    "minimap.selectionHighlight" : Color(0xFF264F78),
    "minimap.errorHighlight" : Color.fromARGB(179, 255, 18, 18),
    "minimap.warningHighlight" : Color(0xFFCCA700),
    "minimap.background" : Colors.black,
    "minimap.foregroundOpacity" : Color(0x0F000000),
    "minimapSlider.background" : Color(0x66797979),
    "minimapSlider.hoverBackground" : Color(0xB2646464),
    "minimapSlider.activeBackground" : Color(0x66BFBFBF),
    "problemsErrorIcon.foreground" : Color(0xFFF14C4C),
    "problemsWarningIcon.foreground" : Color(0xFFCCA700),
    "problemsInfoIcon.foreground" : Color(0xFF3794FF),
    "charts.foreground" : Color(0xFFCCCCCC),
    "charts.lines" : Color(0xB2CCCCCC),
    "charts.red" : Color(0xFFF14C4C),
    "charts.blue" : Color(0xFF3794FF),
    "charts.yellow" : Color(0xFFCCA700),
    "charts.orange" : Color(0xFFd18616),
    "charts.green" : Color(0xFF89D185),
    "charts.purple" : Color(0xFFB180D7),
    "tab.activeBackground": Color(0xFF1E1E1E),
    "tab.unfocusedActiveBackground": Color(0xFF1E1E1E),
    "tab.inactiveBackground": Color(0xFF2D2D2D),
    "tab.unfocusedInactiveBackground": Color(0xFF2D2D2D),
    "tab.activeForeground": Colors.white,
    "tab.inactiveForeground": Color(0x88FFFFFF),
    "tab.unfocusedActiveForeground": Color(0x88FFFFFF),
    "tab.unfocusedInactiveForeground":  Color(0x44FFFFFF),
    "tab.hoverBackground": Colors.black,
    "tab.unfocusedHoverBackground": Colors.black,
    "tab.hoverForeground": Colors.black,
    "tab.unfocusedHoverForeground": Colors.black,
    "tab.border": Color(0xFF252526),
    "tab.lastPinnedBorder": Color(0xFF585858),
    "tab.activeBorder": Colors.black,
    "tab.unfocusedActiveBorder": Colors.black,
    "tab.activeBorderTop": Colors.black,
    "tab.unfocusedActiveBorderTop": Colors.black,
    "tab.hoverBorder": Colors.black,
    "tab.unfocusedHoverBorder": Colors.black,
    "tab.activeModifiedBorder": Color(0xFF3399CC),
    "tab.inactiveModifiedBorder": Color(0x443399CC),
    "tab.unfocusedActiveModifiedBorder": Color(0x883399CC),
    "tab.unfocusedInactiveModifiedBorder": Color(0x443399CC),
    "editorPane.background": Color(0xFF1E1E1E),
    "editorGroup.emptyBackground": Colors.black,
    "editorGroup.focusedEmptyBorder": Colors.black,
    "editorGroupHeader.tabsBackground": Color(0xFF252526),
    "editorGroupHeader.tabsBorder": Colors.black,
    "editorGroupHeader.noTabsBackground": Color(0xFF1E1E1E),
    "editorGroupHeader.border": Colors.black,
    "editorGroup.border": Color(0xFF444444),
    "editorGroup.dropBackground": Color(0x8853595D),
    "editorGroup.dropIntoPromptForeground": Color(0xFFCCCCCC),
    "editorGroup.dropIntoPromptBackground": Color(0xFF252526),
    "editorGroup.dropIntoPromptBorder": Colors.black,
    "sideBySideEditor.horizontalBorder": Color(0xFF444444),
    "sideBySideEditor.verticalBorder": Color(0xFF444444),
    "panel.background": Color(0xFF1E1E1E),
    "panel.border": Color(0x55808080),
    "panelTitle.activeForeground": Color(0xFFE7E7E7),
    "panelTitle.inactiveForeground": Color(0xB2E7E7E7),
    "panelTitle.activeBorder": Color(0xFFE7E7E7),
    "panelInput.border": Colors.black,
    "panel.dropBorder": Color(0xFFE7E7E7),
    "panelSection.dropBackground": Color(0x8853595D),
    "panelSectionHeader.background": Color(0x33808080),
    "panelSectionHeader.foreground": Colors.black,
    "panelSectionHeader.border": Colors.black,
    "panelSection.border": Color(0x55808080),
    "banner.background": Color(0xFF094771),
    "banner.foreground": Colors.white,
    "banner.iconForeground": Color(0xFF3794FF),
    "statusBar.foreground": Color(0xFFFFFFFF),
    "statusBar.noFolderForeground": Color(0xFFFFFFFF),
    "statusBar.background": Color(0xFF007ACC),
    "statusBar.noFolderBackground": Color(0xFF68217A),
    "statusBar.border": Colors.black,
    "statusBar.focusBorder": Color(0xFFFFFFFF),
    "statusBar.noFolderBorder": Colors.black,
    "statusBarItem.activeBackground": Color(0x33FFFFFF),
    "statusBarItem.focusBorder": Color(0xFFFFFFFF),
    "statusBarItem.hoverBackground": Color(0x0FFFFFFF),
    "statusBarItem.compactHoverBackground": Color(0x33FFFFFF),
    "statusBarItem.prominentForeground": Color(0xFFFFFFFF),
    "statusBarItem.prominentBackground": Color(0x88000000),
    "statusBarItem.prominentHoverBackground": Color(0x55000000),
    "statusBarItem.errorBackground": Color(0xFFCC5F49),
    "statusBarItem.errorForeground": Colors.white,
    "statusBarItem.warningBackground": Color(0xFFA47F00),
    "statusBarItem.warningForeground": Colors.white,
    "activityBar.background": Color(0xFF333333),
    "activityBar.foreground": Colors.white,
    "activityBar.inactiveForeground": Color.fromRGBO(255, 255, 255, 0.15),
    "activityBar.border": Colors.black,
    "activityBar.activeBorder": Colors.white,
    "activityBar.activeFocusBorder": Colors.black,
    "activityBar.activeBackground": Colors.black,
    "activityBar.dropBorder": Colors.white,
    "activityBarBadge.background": Color(0xFF007ACC),
    "activityBarBadge.foreground": Colors.white,
    "statusBarItem.remoteBackground": Color(0xFF007ACC),
    "statusBarItem.remoteForeground": Colors.white,
    "extensionBadge.remoteBackground": Color(0xFF007ACC),
    "extensionBadge.remoteForeground": Colors.white,
    "sideBar.background": Color(0xFF252526),
    "sideBar.foreground": Colors.black,
    "sideBar.border": Color(0xFF252526),
    "sideBarTitle.foreground": Colors.black,
    "sideBar.dropBackground": Color(0x8853595D),
    "sideBarSectionHeader.background": Color(0x33808080),
    "sideBarSectionHeader.foreground": Colors.black,
    "sideBarSectionHeader.border": Colors.black,
    "titleBar.activeForeground": Color(0xFFCCCCCC),
    "titleBar.inactiveForeground": Color(0xB2CCCCCC),
    "titleBar.activeBackground": Color(0xFF3C3C3C),
    "titleBar.inactiveBackground": Color(0xB23C3C3C),
    "titleBar.border": Colors.black,
    "menubar.selectionForeground": Color(0xFFCCCCCC),
    "menubar.selectionBackground": Color(0x0FFFFFFF),
    "menubar.selectionBorder": Colors.black,
    "notificationCenter.border": Colors.black,
    "notificationToast.border": Colors.black,
    "notifications.foreground": Color(0xFFCCCCCC),
    "notifications.background": Color(0xFF252526),
    "notificationLink.foreground": Color(0xFFF14C4C),
    "notificationCenterHeader.foreground": Colors.black,
    "notificationCenterHeader.background": Color(0xFF434344),
    "notifications.border": Color(0xFF252526),
    "notificationsErrorIcon.foreground": Color(0xFFF14C4C),
    "notificationsWarningIcon.foreground": Color(0xFFCCA700),
    "notificationsInfoIcon.foreground": Color(0xFF3794FF),
    "window.activeBorder": Colors.black,
    "window.inactiveBorder": Colors.black,
};
